/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aluno.saolucas
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btEmSC = new javax.swing.JButton();
        BtMVC = new javax.swing.JButton();
        BtEmSG = new javax.swing.JButton();
        BtMVG = new javax.swing.JButton();
        BtEmSP = new javax.swing.JButton();
        BtMVP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cachorro");

        jLabel2.setText("Gato");

        jLabel3.setText("Passaro");

        btEmSC.setText("Emitir som");
        btEmSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmSCActionPerformed(evt);
            }
        });

        BtMVC.setText("Mover-se");
        BtMVC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtMVCActionPerformed(evt);
            }
        });

        BtEmSG.setText("Emitir som");
        BtEmSG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEmSGActionPerformed(evt);
            }
        });

        BtMVG.setText("Mover-se");
        BtMVG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtMVGActionPerformed(evt);
            }
        });

        BtEmSP.setText("Emitir som");
        BtEmSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEmSPActionPerformed(evt);
            }
        });

        BtMVP.setText("Mover-se");
        BtMVP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtMVPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btEmSC)
                            .addComponent(BtMVC))
                        .addGap(0, 44, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtEmSG)
                            .addComponent(BtMVG))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtEmSP)
                            .addComponent(BtMVP)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)
                        .addGap(95, 95, 95)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEmSC)
                    .addComponent(BtEmSG)
                    .addComponent(BtEmSP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtMVC)
                    .addComponent(BtMVG)
                    .addComponent(BtMVP))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEmSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmSCActionPerformed
        AçoesDAO objDAO = new AçoesDAO();
        objDAO.SomC();
    }//GEN-LAST:event_btEmSCActionPerformed

    private void BtMVCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMVCActionPerformed
        AçoesDAO objDAO = new AçoesDAO();
        objDAO.MoverC();
    }//GEN-LAST:event_BtMVCActionPerformed

    private void BtEmSGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEmSGActionPerformed
        AçoesDAO objDAO = new AçoesDAO();
        objDAO.SomG();
    }//GEN-LAST:event_BtEmSGActionPerformed

    private void BtMVGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMVGActionPerformed
        AçoesDAO objDAO = new AçoesDAO();
        objDAO.MoverG();
    }//GEN-LAST:event_BtMVGActionPerformed

    private void BtEmSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEmSPActionPerformed
        AçoesDAO objDAO = new AçoesDAO();
        objDAO.SomP();
    }//GEN-LAST:event_BtEmSPActionPerformed

    private void BtMVPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMVPActionPerformed
        AçoesDAO objDAO = new AçoesDAO();
        objDAO.MoverP();
    }//GEN-LAST:event_BtMVPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtEmSG;
    private javax.swing.JButton BtEmSP;
    private javax.swing.JButton BtMVC;
    private javax.swing.JButton BtMVG;
    private javax.swing.JButton BtMVP;
    private javax.swing.JButton btEmSC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
